const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(require.resolve('playwright',{paths:[path.resolve(path.dirname(process.execPath),'../node_modules')]}));
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(require('url').pathToFileURL(path.resolve('mockups/admin/kalendarz/mockup-kalendarz.html')).href);await page.evaluate(()=>document.fonts.ready);
for(const [width,height] of [[1536,726],[1024,484],[1280,605],[853,484],[768,600],[390,844],[320,700]]){await page.setViewportSize({width,height});for(const full of [false,true]){await page.evaluate(full=>{state.fullscreen=full;render()},full);const m=await page.evaluate(()=>{const v=document.querySelector('#viewport'),q=document.querySelector('.queue'),f=document.querySelector('.footer');return {width:innerWidth,height:innerHeight,full:state.fullscreen,grid:Math.round(v.clientHeight),pageWidth:document.documentElement.scrollWidth,pageHeight:document.documentElement.scrollHeight,queueBottom:q.getBoundingClientRect().bottom,footerTop:f.getBoundingClientRect().top}});console.log(m);assert.ok(m.pageWidth<=width+1);assert.ok(m.pageHeight<=height);assert.ok(m.queueBottom<=m.footerTop);assert.ok(m.grid>=150)}}
await page.setViewportSize({width:1024,height:484});await page.evaluate(()=>{state.fullscreen=true;render()});if(process.env.COMPACT_SCREENSHOT)await page.screenshot({path:process.env.COMPACT_SCREENSHOT});
await page.evaluate(()=>{state.selected='pestka';state.queue=true;render()});assert.ok(await page.locator('#viewport').evaluate(e=>e.clientHeight)>=190);assert.ok(await page.locator('.legend').isVisible());assert.equal(await page.locator('.legend button').first().evaluate(e=>getComputedStyle(e).borderLeftWidth),'5px');await page.locator('#close-panel').click();await page.locator('#queue-toggle').click();
await page.locator('#viewport').evaluate(e=>{e.scrollTop=180;e.scrollLeft=300});const sticky=await page.evaluate(()=>{const v=document.querySelector('#viewport').getBoundingClientRect(),t=document.querySelector('.top-axis').getBoundingClientRect(),l=document.querySelector('.left-axis').getBoundingClientRect();return [t.top-v.top,l.left-v.left]});assert.ok(sticky.every(x=>Math.abs(x)<3));
const before=await page.locator('#viewport').evaluate(e=>e.clientHeight);await page.locator('#queue-toggle').click();assert.ok(await page.locator('#viewport').evaluate(e=>e.clientHeight)>=before-106);assert.ok(await page.evaluate(()=>document.querySelector('#viewport').getBoundingClientRect().bottom<=document.querySelector('.queue').getBoundingClientRect().top));await page.locator('[data-assign="figa,felek"]').click();assert.equal(await page.locator('#queue-toggle').getAttribute('aria-expanded'),'false');await page.locator('.box-head[data-box="3"]').click();assert.equal(await page.locator('#target-box').inputValue(),'3');assert.ok(await page.locator('#save-move').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight));await page.locator('#save-move').click();assert.equal(await page.locator('[data-pet="figa"].normal').count(),1);await page.locator('#queue-toggle').click();
await page.locator('#reset').click();await page.locator('[data-orientation="v3"]').click();await page.locator('[data-orientation="v4"]').click();await page.locator('[data-pet="luna"].normal').click();await page.locator('#begin-move').click();await page.locator('#target-box').selectOption('2',{force:true});await page.locator('#save-move').click();assert.ok((await page.locator('#toast').textContent()).includes('Box 2'));await page.evaluate(()=>{state.fullscreen=false;render()});await page.locator('#menu').click();assert.equal(await page.locator('.sidebar').evaluate(e=>e.getBoundingClientRect().left),0);await page.keyboard.press('Escape');assert.equal(await page.locator('.sidebar.open').count(),0);assert.deepEqual(errors,[]);await browser.close();console.log('PASS');})().catch(e=>{console.error(e);process.exit(1)});
